services:
  plutus-db:
    image: postgres:16
    container_name: plutus-db
    environment:
      POSTGRES_DB: plutus
      POSTGRES_USER: plutus_user
      POSTGRES_PASSWORD: plutus_pass
    ports:
      - "5432:5432"
    volumes:
      - plutus_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plutus_user -d plutus"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  plutus_pgdata:
